spring:
  config:
    import: "optional:file:.env[.properties]"
  
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/spring
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  data:
    redis.url: redis://${REDIS_URL}

  security:
    user:
      name: admin
      password: 123

  mail:
    host: ${EMAIL_HOST}
    port: 587 # Default port
    username: ${EMAIL_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh

logging:
  level.org.springframework.jdbc.core: DEBUG
  level.org.springframework.jdbc.core.JdbcTemplate: DEBUG

springdoc:
  api-docs.path: /api-docs

jwt:
  secret: ${JWT_SECRET}
  expiration: 30*1000

cloudinary:
  url: ${CLOUDINARY_URL}