name: J2EE_Backend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-springboot:
    name: Build spring boot 3.5.x app with gradle
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-versions: [21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-versions }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compile source code
        run: gradle compileJava
